x-redash-image: &x-redash-image "redash/redash:8.0.0.b32245"

x-redash-common-env: &x-redash-common-env
  PYTHONUNBUFFERED: "0"
  REDASH_LOG_LEVEL: "INFO"
  REDASH_REDIS_URL: "redis://redis:6379/0"

services:
  adhoc-worker:
    hostname: redash-adhoc-worker
    networks: [dfc]
    image: *x-redash-image
    restart: unless-stopped
    command: ["worker"]
    environment:
      <<: *x-redash-common-env
      QUEUES: queries
      WORKERS_COUNT: "2"
    env_file:
      - ./secrets/redash.env

  scheduled-worker:
    hostname: redash-scheduled-worker
    networks: [dfc]
    image: *x-redash-image
    restart: unless-stopped
    command: ["worker"]
    environment:
      <<: *x-redash-common-env
      QUEUES: scheduled_queries,schemas
      WORKERS_COUNT: "1"
    env_file:
      - ./secrets/redash.env

  scheduler:
    hostname: redash-scheduler
    networks: [dfc]
    image: *x-redash-image
    restart: unless-stopped
    command: ["scheduler"]
    environment:
      <<: *x-redash-common-env
      QUEUES: celery
      WORKERS_COUNT: "1"
    env_file:
      - ./secrets/redash.env

  server:
    hostname: redash
    networks: [dfc]
    image: *x-redash-image
    restart: unless-stopped
    command: ["server"]
    environment:
      <<: *x-redash-common-env
      REDASH_WEB_WORKERS: "1"
    env_file:
      - ./secrets/redash.env

  nginx:
    hostname: redash-nginx
    networks: [dfc]
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.redash-nginx.loadbalancer.server.port=80"
      - "traefik.http.routers.redash-nginx.rule=Host(`redash.dataforchange.org.il`)"
      # - "traefik.http.routers.anyway-reports.tls=true"
      # - "traefik.http.routers.anyway-reports.tls.certresolver=dfc"
    # pulled Nov 1, 2021
    image: redash/nginx:latest@sha256:4eaaa7af6476b0422058b0022661ad6129dfbf9065c506fb0904bbf0a16f2007
    restart: unless-stopped
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro

  postgres:
    hostname: redash-postgres
    networks: [dfc]
    image: postgres:9.6-alpine@sha256:8c3455a1c953c7c4fbcedca28a0c9c665cb6175934148335b3b86df5d106b9b5
    restart: unless-stopped
    env_file:
      - ./secrets/redash.env
    volumes:
      - /data/redash-postgres/redash_postgres:/var/lib/postgresql/data

  redis:
    hostname: redash-redis
    networks: [dfc]
    image: redis:5.0-alpine@sha256:cb5840073dc475b45bf856eb666f5e4d19e3b1ae882e0f3a1396d399cfa23702
    restart: unless-stopped

networks:
  dfc:
    external: true

x-on-file-change:
  - "nginx-default.conf": docker compose restart nginx

x-files:
  nginx-default.conf: {}

x-secrets:
  env_files:
    redash:
      POSTGRES_PASSWORD: "vault:projects/k8s/redash/secret:postgres_password"
      REDASH_COOKIE_SECRET: "vault:projects/k8s/redash/secret:cookie_secret"
      REDASH_SECRET_KEY: "vault:projects/k8s/redash/secret:secret_key"
      REDASH_DATABASE_URL: "vault:projects/k8s/redash/secret:redash_database_url"
      REDASH_GOOGLE_CLIENT_ID: "vault:projects/k8s/redash/secret:google_auth_client_id"
      REDASH_GOOGLE_CLIENT_SECRET: "vault:projects/k8s/redash/secret:google_auth_client_secret"
