name: anyway CI
on:
  push:
    paths:
      - '.github/workflows/anyway.yml'
      - 'apps/anyway/**'
jobs:
  anyway:
    runs-on: ubuntu-22.04
    steps:
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VAULT_CLI_VERSION: "1.10.4"
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        # python3 vault/create_policy.py readonly
        # python3 vault/create_approle.py terraform_readonly readonly
        VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
        VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
        CI: "true"
      run: |
        curl -s https://raw.githubusercontent.com/OriHoch/uumpa-ci-toolbox/65a0704332e63d51f63981dbb25cd83682dc4078/bin/github_actions_install.sh \
          | bash -s 4ed9d7055f0aa9629de1291fe0f42e154709b0b6 OriHoch/uumpa-ci-toolbox &&\
        uci github actions self-checkout --config-user-name "dfc-iac-anyway-ci" &&\
        uci vault install --version $VAULT_CLI_VERSION &&\
        pip install -r requirements.txt &&\
        export VAULT_TOKEN="$(uci vault approle-login $VAULT_ROLE_ID $VAULT_SECRET_ID)" &&\
        bin/apps.py create_selenium_data_folder &&\
        bin/apps.py deploy_app anyway &&\
        bin/apps.py compose anyway ps
